version: '3.8'

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: goshoes_18.3
            MYSQL_DATABASE: goshoes
            MYSQL_USER: user_goshoes_18.3
            MYSQL_PASSWORD: password_goshoes_18.3
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    redis-data:
        driver: local
    mysql-data:
        driver: local
