version: "3.8"

services:
    app:
        image: php:8.1-fpm
        container_name: laravel_app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: goshoes
            MYSQL_USER: root
            MYSQL_PASSWORD:
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
