openapi: 3.0.3
info:
  title: 'POP 18.3 Documentation API'
  description: 'POP 18.3 API Documentation for developers to integrate with our API'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:80'
paths:
  /api/test:
    get:
      summary: 'Test API'
      operationId: testAPI
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "[\n  {\n   'message' => 'Hello John Doe!',\n  }\n]"
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthorized
                properties:
                  message:
                    type: string
                    example: Unauthorized
      tags:
        - Test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: 'John Doe'
              required:
                - name
      security: []
tags:
  -
    name: Test
    description: ''
