<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;

class UserSeeder extends Seeder
{

    public function run()
{
    User::insert([
        [
            'id' => 1,
            'name' => 'Admin',
            'email' => 'admin@gmail.com',
            'phone' => '0123456789',
            'password' => bcrypt('Admin@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Super Admin Account',
            'birth_date' => '1990-01-01',
            'gender' => 'male',
            'role' => 'super-admin'
        ],
        [
            'id' => 2,
            'name' => 'John Doe',
            'email' => 'john@gmail.com',
            'phone' => '0123456781',
            'password' => bcrypt('User@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Regular customer',
            'birth_date' => '1995-05-15',
            'gender' => 'male',
            'role' => 'admin'
        ],
        [
            'id' => 3,
            'name' => 'Jane Smith',
            'email' => 'jane@gmail.com',
            'phone' => '0123456782',
            'password' => bcrypt('User@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Shoe lover',
            'birth_date' => '1992-08-20',
            'gender' => 'female',
            'role' => 'admin'
        ],
        [
            'id' => 4,
            'name' => 'Sarah Manager',
            'email' => 'sarah@gmail.com',
            'phone' => '0123456783',
            'password' => bcrypt('Manager@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Store Manager',
            'birth_date' => '1988-03-10',
            'gender' => 'female',
            'role' => 'admin'
        ],
        [
            'id' => 5,
            'name' => 'Mike Johnson',
            'email' => 'mike@gmail.com',
            'phone' => '0123456784',
            'password' => bcrypt('User@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Sneaker collector',
            'birth_date' => '1993-12-05',
            'gender' => 'male',
            'role' => 'user'
        ],
        [
            'id' => 6,
            'name' => 'Emily Brown',
            'email' => 'emily@gmail.com',
            'phone' => '0123456785',
            'password' => bcrypt('User@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Fashion enthusiast',
            'birth_date' => '1997-07-25',
            'gender' => 'female',
            'role' => 'user'
        ],
        [
            'id' => 7,
            'name' => 'David Wilson',
            'email' => 'david@gmail.com',
            'phone' => '0123456786',
            'password' => bcrypt('Staff@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Sales Staff',
            'birth_date' => '1994-09-15',
            'gender' => 'male',
            'role' => 'user'
        ],
        [
            'id' => 8,
            'name' => 'Lisa Anderson',
            'email' => 'lisa@gmail.com',
            'phone' => '0123456787',
            'password' => bcrypt('User@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Regular shopper',
            'birth_date' => '1996-04-30',
            'gender' => 'female',
            'role' => 'user'
        ],
        [
            'id' => 9,
            'name' => 'Tom Harris',
            'email' => 'tom@gmail.com',
            'phone' => '0123456788',
            'password' => bcrypt('User@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Sports enthusiast',
            'birth_date' => '1991-11-20',
            'gender' => 'male',
            'role' => 'user'
        ],
        [
            'id' => 10,
            'name' => 'Mary Taylor',
            'email' => 'mary@gmail.com',
            'phone' => '0123456789',
            'password' => bcrypt('Staff@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Customer Service',
            'birth_date' => '1989-06-12',
            'gender' => 'female',
            'role' => 'user'
        ],
        [
            'id' => 11,
            'name' => 'Peter Clark',
            'email' => 'peter@gmail.com',
            'phone' => '0123456790',
            'password' => bcrypt('User@123'),
            'is_deleted' => 0,
            'auth_provider' => 'local',
            'email_verified_at' => now(),
            'remember_token' => null,
            'avt' => null,
            'facebook_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
            'bio' => 'Casual shopper',
            'birth_date' => '1998-02-28',
            'gender' => 'male',
            'role' => 'user'
        ]
    ]);
}
}
