name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml exec app php artisan migrate --force
          docker-compose -f docker-compose.yml exec frontend npm install
          docker-compose -f docker-compose.yml exec frontend npm run build

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml exec app php artisan test

      - name: Shutdown Docker Compose
        run: |
          docker-compose -f docker-compose.yml down
